MODEL:
    IN_CHANNELS: 1 #husk å endre i contractblock også
    OUT_CHANNELS: 4 #husk å endre i expandblock også
INPUT:
    IMAGE_SIZE: [300, 300]
DATASETS:
    TRAIN_IMAGES: '../../../../work/datasets/medical_project/CAMUS'

# UNETSTRUCTURE:
#     CONTRACTBLOCK:  [[1, 32, 7, 3], #in channels er første verdi i denne listen
#                     [32, 64, 3, 1],
#                     [64, 128, 3, 1],
#                     [128,256,3,1],
#                     [256,512,3,1]]

#     EXPANDBLOCK: [[512,256,3,1],
#                 [512,128,3,1],
#                 [256, 64, 3, 1],
#                 [128, 32, 3, 1],
#                 [64, 4 , 3, 1]] #out channels er andre verdi i denne listen
    #TEST: ("mnist_detection_val", )
# SOLVER:
    # MAX_ITER: 15000
    # GAMMA: 0.1
    # BATCH_SIZE: 16
    # LR: 2e-3
    # WEIGHT_DECAY: 5e-4
    # WEIGHT_DECAY: 1e-3
    # MOMENTUM: 0.9
OUTPUT_DIR: 'outputs/UNET_base_model'
LOGGER:
    SAVE_DIR: True
  
