MODEL:
    IN_CHANNELS: 1 #husk 책 endre i contractblock ogs책
    OUT_CHANNELS: 4 #husk 책 endre i expandblock ogs책
MODEL:
    CLASSES: [1, 2, 3]

PREPROCESSING:
    ELASTICDEFORM:
      ENABLE: True
      ALPHA: 300
      SIGMA: 25
      ALPHA_AFFINE: 1
      PROBABILITY: 0.5
OUTPUT_DIR: 'outputs/Data_aug_model'
LOGGER:
    SAVE_DIR: True