MODEL:
    IN_CHANNELS: 1 #husk 책 endre i contractblock ogs책
    OUT_CHANNELS: 4 #husk 책 endre i expandblock ogs책
DATASETS:
    TRAIN_IMAGES: '../../../../work/datasets/medical_project/CAMUS'
MODEL:
    CLASSES: [1, 2, 3]
PREPROCESSING:
    ISOTROPIC_PIXEL_SIZE:
        ENABLE: True
        SIZE: 384
        PROBABILITY: 1

    ELASTICDEFORM:
      ENABLE: True
      ALPHA: 300
      SIGMA: 30
      ALPHA_AFFINE: 1
      PROBABILITY: 0.5
OUTPUT_DIR: 'outputs/UNET_base_model'
LOGGER:
    SAVE_DIR: True