MODEL:
    IN_CHANNELS: 1 #husk å endre i contractblock også
    OUT_CHANNELS: 4 #husk å endre i expandblock også
DATASETS:
    TRAIN_IMAGES: '../../../../work/datasets/medical_project/CAMUS'
MODEL:
    CLASSES: [1, 2, 3]
UNETSTRUCTURE:
    CONTRACTBLOCK:  [[1, 32, 7, 3], #in channels er første verdi i denne listen
                    [32, 64, 3, 1],
                    [64, 128, 3, 1],
                    [128,256,3,1]]

    EXPANDBLOCK: [[256,128,3,1],
                [256, 64, 3, 1],   
                [128, 32, 3, 1],
                [64, 4 , 3, 1]] #out channels er andre verdi i denne listen
OUTPUT_DIR: 'outputs/Deeper_Network_model'
LOGGER:
    SAVE_DIR: True