PREPROCESSING:
  RESIZE:
    FX: 0.6
    FY: 0.6
  ROTATE:
    ENABLE: True
    LIMIT: 6
    BORDER_MODE: 0 #cv2.BORDER_CONSTANT
    PROB: 0.25
  ELASTICDEFORM:
    ENABLE: True
    ALPHA: 270
    SIGMA: 25
    ALPHA_AFFINE: 1
    PROBABILITY: 0.25
  RANDOMCROP:
    ENABLE: True
    X_RESIZE: 0.8
    Y_RESIZE: 0.8
    PROB: 0.25

LOGGER:
  SAVE_DIR: True


OUTPUT_DIR: 'outputs/backbone_densenet121_final_w_normalize'

UNETSTRUCTURE:
  CONTRACTBLOCK : [[cfg.MODEL.IN_CHANNELS, 32, 7, 3], 
                                    [32, 64, 3, 1],
                                    [64, 128, 3, 1],
                                    [64, 128, 3, 1],
                                    [64, 128, 3, 1]]     #number of layers should equal the depth of the backbone model



MODEL:
  BACKBONE:
    USE : True
    NET : 'densenet121'      
    PRETRAINED : True
    ENCODER_FREZE : False
    DECODER_FILTERS : (256, 128, 64, 32, 16)
    PARAMETRIC_UPSAMPLING : True
    SHORTCUT_FEATURES : 'default'
    DECODER_USE_BATCHNORM : True
    USE_NORMALIZATION : True

SOLVER:
  LR : 1e-4
  MAX_ITER : 8000
  MAX_MINUTES : 120

FIND_LR_EPOCH : 0

SCHEDULER : True
